### ISSUE TITLE
Request Instance Page looks broken

### ISSUE THREAD

**Issue by erikzrekz** [openlawteam/openlaw-issue-tracker#10]
Was browsing around and saw this page. 

![screen shot 2018-05-20 at 12 50 55 pm](https://user-images.githubusercontent.com/3126690/40281903-7fd3c272-5c2c-11e8-8d98-9cc972d3f6f4.png)

I inspected element and removing the applied `width` property from .container and that seemed to fix it. But likely that it might be breaking things elsewhere.

```
@media screen and (min-width: 1024px)
.container {
    max-width: 960px;
    width: 960px;
}
```

**Comment by outkaj** [comment]
thanks for flagging - we'll look into it!

**Comment by outkaj** [comment]
Hey, this is fixed in a version which will be released soon! Closing
