### ISSUE TITLE
Accepted passwords for signup incompatible with password managers

### ISSUE THREAD

**Issue by Cygnusfear** [openlawteam/openlaw-issue-tracker#14]
Password must be at least 8 characters with one upper-case letter, one lower-case letter, one number, and one accepted special character (!@#$&*/).

Above check for passwords has three issues:
- Password generators/managers will generate passwords with characters such as .:; this means users using a password manager (which is considered good password hygiene) will have a hard time generating a password (read: impossible)
- Obliging the user to include these characters is neither useful nor helps with proper password hygiene, forcing all users to include one out of 7 extra characters does not increase user security or better password hygiene.
- Very big UX issue: No tooltip to actually tell the user what is wrong with the password, need to scan the page for that subscript. Password confirmation check is positive even when password is wrong.

**Comment by outkaj** [comment]
Hi @Cygnusfear - thanks for your thoughtful feedback. We'll look into these issues you've raised and update here accordingly.

**Comment by outkaj** [comment]
@Cygnusfear I've fixed this & it should be good for the next release (this Friday), so going to go ahead and close. Thanks again for reporting!
