### ISSUE TITLE
Can't include descriptions in YesNo variables within a Structure

### ISSUE THREAD

**Issue by bwiles81** [openlawteam/openlaw-issue-tracker#17]
This throws "error in the constructor for Structured Type":

[[Person: Structure(
   Name: Text;
   Address: Address;
   Member: YesNo "Is this person a member?"
   )]]

***

This works fine:

[[Person: Structure(
   Name: Text;
   Address: Address;
   Member: YesNo
   )]]

**Comment by outkaj** [comment]
Closing as a fix for this issue was merged in past.
