### ISSUE TITLE
password reset fails too late

### ISSUE THREAD

**Issue by humbitious** [openlawteam/openlaw-issue-tracker#2]
As a user who isn't sure which email I used for my username, I need the password reset feature to fail my reset request early in the process, so that I don't get all the way to the reset email coming to me and me creating a new password before I get the "username doesn't exist" error statement.

**Comment by outkaj** [comment]
Great point! We'll implement that.

**Comment by outkaj** [comment]
We've implemented this and it will be part of our next deployment. Thanks @humbitious for the suggestion.
