### ISSUE TITLE
Clause type spits error

### ISSUE THREAD

**Issue by bwiles81** [openlawteam/openlaw-issue-tracker#21]
I created this template, entitled "Choice of Law and Forum"
This Agreement shall be governed by the laws of the State of [[Governing Law]], without giving effect to the principles of conflict of laws.  With respect to any disputes arising out of or related to this Agreement, the parties consent to the exclusive jurisdiction of, and venue in, the courts located in [[Choice of Forum]].  Each party hereto further hereby irrevocably and unconditionally waives any objection to the laying of venue of any action, suit or proceeding arising out of or relating to this Agreement in the federal and state courts located in [[Choice of Forum]] and hereby further irrevocably and unconditionally waives and agrees not to plead or claim in any such court that any such action, suit or proceeding brought in any such court has been brought in any inconvenient forum.

In the contract body, I tried

[[_: Clause("Choice of Law and Forum")]]

and [[clause: Clause("Choice of Law and Forum")]]

both give this error: unexpected condition, section not found in processed sections

**Comment by outkaj** [comment]
@bwiles81 thanks for this report. There are few bugs we're looking into currently regarding the Clause feature.

**Comment by outkaj** [comment]
we'll let you know once it's working!

**Comment by outkaj** [comment]
@bwiles81 do you mind trying again? We have fixed some issues with the Clause type in our new release

**Comment by outkaj** [comment]
closing as a fix for this will be released shortly
