### ISSUE TITLE
Allow for digital notary to be added to contract

### ISSUE THREAD

**Issue by jdville03** [openlawteam/openlaw-issue-tracker#5]
- In addition to digital signatures, allow a contract to receive a digital notary.

- Some legal documents are required to be notarized to be legally binding. A few jurisdictions currently allow for digital notaries.

-  This suggestion came up in the context of death certificates. It would be nice to see this feature added in the near term.

**Comment by Ro5s** [comment]
@jdville03 I am playing with Solidity version of manuel araoz's 'proof of existence' digital notary service. See background here: https://blog.zeppelin.solutions/the-hitchhikers-guide-to-smart-contracts-in-ethereum-848f08001f05

See OL tester here: https://app.openlaw.io/template/Notarizer

Is this related to your idea here?
