### ISSUE TITLE
Require signatories to sign contract in certain order

### ISSUE THREAD

**Issue by jdville03** [openlawteam/openlaw-issue-tracker#6]
- Some legal documents with multiple signatories need to be signed in a certain order to be enforceable.

- This suggestion came up in the context of death certificates. It would be nice to see this feature added in the near term.

**Comment by adridadou** [comment]
We could use the flow to do that. I think it will need some testing / work but it shouldn't be a big thing.

Basically you will have something like that

[[First Signatory:Identity]]

{{First Signatory.hasSigned => [[Second Signatory:Identity]]}}


and this way, the second signatory is taken into account only when the first one has signed

**Comment by outkaj** [comment]
We'll handle this via flow - don't need a distinct issue. Closing
